#!/usr/bin/env bash
# Re-download every pinned artifact for every supported architecture and
# rewrite hack/tools.sha256. Run it after bumping a version in hack/tools.list.
set -euo pipefail

# shellcheck source=hack/tools-lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/tools-lib.sh"

ARCHES=(amd64 arm64)
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

out="${tmp}/tools.sha256"
{
  echo "# Generated by hack/refresh-checksums.sh - do not edit by hand."
  echo "# Columns: name arch sha256"
} > "$out"

while IFS='|' read -r name _ version url _; do
  for a in "${ARCHES[@]}"; do
    arch_vars "$a"
    resolved="$(expand "$url" "$version")"
    echo ">> ${name} ${version} (${a})" >&2
    file="${tmp}/artifact"
    curl --fail --silent --show-error --location \
         --retry 3 --retry-delay 2 --max-time 600 \
         --output "$file" "$resolved"
    printf '%s %s %s\n' "$name" "$a" "$(sha256_of "$file")" >> "$out"
    rm -f "$file"
  done
done < <(tools_entries)

mv "$out" "$TOOLS_SUMS"
echo "wrote ${TOOLS_SUMS}" >&2
